Document: disque
Title: Debian disque Manual
Author: <insert document author here>
Abstract: This manual describes what disque is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/disque/disque.sgml.gz

Format: postscript
Files: /usr/share/doc/disque/disque.ps.gz

Format: text
Files: /usr/share/doc/disque/disque.text.gz

Format: HTML
Index: /usr/share/doc/disque/html/index.html
Files: /usr/share/doc/disque/html/*.html
